### PR TITLE
[FW][FIX] hr_timesheet_attendance_ux: avoid problems when the hr_holidays module is not installed

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/hr#35

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/hr/pull/36).

**Comment by fw-bot-adhoc** [comment]
Ping @augusto-weiss, @Bruno-Zanotti cherrypicking of pull request ingadhoc/hr#35 failed.

stdout:
```
Auto-merging hr_timesheet_attendance_ux/models/account_analytic_line.py
Auto-merging hr_timesheet_attendance_ux/__manifest__.py
CONFLICT (content): Merge conflict in hr_timesheet_attendance_ux/__manifest__.py

```

stderr:
```
18:32:57.736502 git.c:439               trace: built-in: git cherry-pick 6d249cf4520a3af1ca1e5414077ac6fd93c8826c
error: could not apply 6d249cf... [FIX] hr_timesheet_attendance_ux: avoid problems when the hr_holidays module is not installed
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
