### PR TITLE
[FIX] hr_timesheet_attendance_ux: filtered holiday lines

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/hr/pull/33).

**Comment by augusto-weiss** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
