### PR TITLE
[REF] hr_holidays_ux: clean up and minor refactor logic

### PR DESCRIPTION
**Pull request by ced-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/hr/pull/43).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@Bruno-Zanotti you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: you are not allowed to override this status.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
